version: '3.8'

services:
  mantenimiento_local:
    image: mysql
    env_file: ./.env
    restart: always
    environment:
      - MYSQL_PASSWORD=$MYSQLDB_LOCAL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_LOCAL_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_LOCAL_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_LOCAL_PORT